# Generated by Django 6.0.2 on 2026-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suite_code',
            field=models.CharField(blank=True, help_text='Unique code for the suit/product', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('winter', 'Winter Collection'), ('summer', 'Summer Collection')], default='suits', max_length=50),
        ),
    ]
